.TH SHARP-USER-SETUP "1" "April 2020" "sharp-user-setup version 10.3.10" "User Commands"
.SH NAME
sharp-user-setup \- script to setup the SharpBang desktop
.SH SYNOPSIS
.B sharp-user-setup
.RI [ OPTION ].\|.\|.
.SH DESCRIPTION
.PP
.BR sharp\-user\-setup () 
is a script to populate a new user's home directory using template files from
.IR /usr/share/sharpbang/skel/ .
.PP
Normally this script is run automatically on a user's first login and inhibited thereafter by a flag file at 
.IR ~/.config/sharpbang/sharp\-setup .
.PP
It can, however, be run again by a user to update their config files from a new version of sharp\-configs. In this case backups will be made of any files which are overwritten.
.PP
If the user has already made extensive changes to their config files it would be better to copy in new settings from 
.I /usr/share/sharpbang/skel/
by hand.
.SH OPTIONS
.TP
.BR \-f ", " \-\^\-firstrun
Copy files from 
.I /usr/share/sharpbang/skel/ 
to 
.IR $HOME , 
action will be aborted if 
.I ~/.config/sharpbang/sharp\-setup
exists.
.TP
.BR \-h ", " \-\^\-help
Display usage information.
.TP
.BR \-r ", " \-\^\-refresh
Copy any files in 
.I /usr/share/sharpbang/skel/
which are different from those in 
.IR $HOME .
Overwritten files will be backed up.
.TP
.BR \-v ", " \-\^\-verbose
Display verbose messages about the copy operation.
.TP
.BR \-V ", " \-\^\-version
Output version information and exit.
.SH "EXIT STATUS"
.TP
.B 0
Successful program execution.
.TP
.B 64
Unrecognised option supplied.
.TP
.B 70
Copy operation failed.
.TP
.B 73
Action inhibited by 
.IR ~/.config/sharpbang/sharp-setup .
.TP
.B 77
Program run by root, unprivileged user expected.
.TP
.B 78
User's home directory is not set or does not exist.
.SH ENVIRONMENT
.PP
The behaviour of
.BR sharp-user-setup ()
is affected by the following environment variables:
.TP
.B backup_suffix
Suffix applied to any pre-existing files in the user's home directory that are overwritten by 
.BR sharp-user-setup (). 
If empty it is set to 
.IR ~$(\ date\ +%F@%T\ ) .
.TP
.B sharp_skel
Directory from which the various configuration files are copied, requires trailing slash. If empty it is set to 
.IR /usr/share/sharpbang/skel/ .
.SH BUGS
Probably. If any problems are found please open an issue at
.BR https://github.com/head-on-a-stick/sharp-configs .
